spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    username: root

  jpa:
    hibernate:
      ddl-auto: update

#  security:
#    user:
#      name: admin
#      password: 123456
server:
  port: 18900

